### ISSUE TITLE
Fallback for unreachable storers

### ISSUE THREAD

**Issue by stpp2** [caddyserver/cache-handler#101]
Hi,

First of all, thanks @darkweak and the Caddy team for all the hard work.
I'm trying to implement the Cache Handler on a Caddy reverse proxy and have a quick question (not really an issue, but thought it might still be relevant enough to post here).

I've experimented a little bit and seems like Caddy fails to build when the `storer` isn't available. (FWIW I tried `go-redis`).
Is there a way to work around this and make sure Caddy always starts no matter if the `storer` is unavailable or not configured properly?

Ideally if my `storer` becomes unreachable (either when starting the server or while Caddy is already running) - Caddy would continue to work, though without cache and without throwing fatal errors.

I know there's the `storers.fallback` option, but not sure if this works with just one storer or if it would prevent fatal errors during start up.

P.S. - two very minor comments on the `Souin` repo -
1. Noticed for naming you sometimes go with `storers` and sometimes with `storages`, might be better to use the same term unless I'm missing something here?
2. The "Storages" link on Souin readme file doesn't work (https://github.com/darkweak/souin?tab=readme-ov-file#storages)

Thanks!

**Comment by darkweak** [comment]
@stpp2 I checked the code and there are no panic. Btw it should fallback on the default storage if none are available during the boot.

**Comment by darkweak** [comment]
@stpp2 No you can't disable the storage. But keep in mind that it will be created only if no other valid storages are used.
