### ISSUE TITLE
Securing access to the Souin API

### ISSUE THREAD

**Issue by mac-chaffee** [caddyserver/cache-handler#106]
Hello! I was excited to learn this repo exists since it makes caching very simple!

I'm looking for ways to avoid exposing the Souin API to the internet so that not just anyone can purge the cache and possibly overload my website. By default, when you enable the API, it will be exposed as an additional route alongside the rest of the application, which I want to avoid:

```
{
	cache {
	  ttl 120s
		otter
		api {
			souin
		}
	}
}

localhost {
 	cache
	respond "Hello World!"
}
```

```
curl -k https://localhost/souin-api/souin/surrogate_keys
{}
```

After the deprecation of Souin's [security endpoint which uses JWTs](https://github.com/darkweak/souin/pull/188), sounds like we're supposed to protect the API by using Caddy itself, but I'm not sure how to do that.

Ideally I'd like the API to be reachable only on localhost or maybe on a different port number. I see that Caddy supports [matchers](https://caddyserver.com/docs/caddyfile/matchers) that could be used to [protect normal routes](https://caddy.community/t/how-to-stop-remote-access/8066/2), but since the `cache.api` config has to be global, I'm not sure how to expose it in a dedicated site block.

Does anyone from the community have an example of how to do this? Thanks in advance!

**Comment by mohammed90** [comment]
I wish there was more control over the API endpoint. I also wish it was exposed on the admin interface (default 2019), which offers remote administration feature with mTLS authentication and ACL (I discuss this capability [here](https://caddy.community/t/separation-of-duty-with-caddy-remote-administration/24684)).

In its current form, I'd block access to the Souin API with a matcher on the main site, and use the cache handler on another site with mTLS enabled on it. Putting this together develops this Caddyfile:

```caddyfile
{
	cache {
	  ttl 120s
		otter
		api {
			souin
		}
	}
}

example.com {
  @souinApi path /souin-api*
   handle @souinApi {
         respond 405
   }
   handle {
       	cache
       	respond "Hello World!"
   }
}

souin.example.com {
    tls {
        client_auth {
              mode require_and_verify
              # pick one from here: https://caddyserver.com/docs/caddyfile/directives/tls#trust-pool-providers
              trust_pool <pool config>
        }
    }
    cache
}
```

This config protects the Souin API with mTLS.

P.S.: Excuse the formatting. I'm typing on the phone.

**Comment by mac-chaffee** [comment]
Ahh this seems to work! The directive ordering puzzle can be solved by using `route`:

```caddy
{
	cache {
		ttl 120s
		otter
		api {
			souin
		}
	}
}

localhost {
	route {
		@souinApi path /souin-api/*
		basic_auth @souinApi {
			testuser $2a$14$i1G0lil5qti7qahb4.Kte.wP/3O8uaStduzhBBtuDUZhMJeSjxbqm
		}
		cache {
			regex {
				exclude /check
			}
		}
		respond "Hello World!"
	}
}
```
Then the API can be accessed like this:

```
curl -ik -X PURGE -u testuser:password https://localhost/souin-api/souin/flush
```

Looks like it's currently impossible to move the API routes to a different port because the API handler and the cache handler are [part of the same Golang function](https://github.com/darkweak/souin/blob/2968d51eef04b31925352ac4aaf815ea49f4efbd/pkg/middleware/middleware.go#L565). But we can use things like `basic_auth`, `remote_ip`, `forward_auth`, etc.
