### ISSUE TITLE
Set custom headers in cache config

### ISSUE THREAD

**Issue by stpp2** [caddyserver/cache-handler#108]
Hi,

Thanks for your work! 

Not an issue/bug, but I'm playing around with the cache handler module and figured it would be really great (for my use case) to set custom headers (not cache-related headers) to the cache service reqs.

(For what it's worth, I think that even a regular Caddy matcher that would only apply to the cache-related requests and can set a custom header would work)

Is there anything to make than happen somehow?

Thanks!

**Comment by darkweak** [comment]
Hey @stpp2 what do you want to do? Can you give me a request/response to illustrate your mind?

**Comment by francislavoie** [comment]
I don't think I really understand the question. But do you mean you want the cache to store a extra header in addition to the one your upstream would have written? What does your entire config look like? It matters to what we can suggest as a solution.

**Comment by francislavoie** [comment]
I don't follow. Redis doesn't speak HTTP, so why would it care about headers?

Do you mean like "only include a response header to the client when it _was_ cached" or something like that? Can you be more specific?

**Comment by darkweak** [comment]
@stpp2 Do you want to know when it's stored or when it serves cached responses?

**Comment by darkweak** [comment]
What is the use case? To have some metrics?
You can detect if it has been stored reading the `Cache-Status` HTTP response header that should have the `stored` directive.

**Comment by darkweak** [comment]
How do you sync the cache between multiple instances? Why not using a redis cluster that can be accessed by all your instances?

**Comment by francislavoie** [comment]
Like I said, directive order. `cache` is ordered before `rewrite` but `intercept` is after. See https://caddyserver.com/docs/caddyfile/directives#directive-order and https://github.com/caddyserver/cache-handler/blob/507cbf6c1f4d49989b9c8519b2e45139a035782c/httpcache.go#L27

You need to wrap both in a `route`, or set `intercept` to be higher, or `cache` to be after `intercept`.
