### ISSUE TITLE
Issues connecting to Go-Redis db

### ISSUE THREAD

**Issue by stpp2** [caddyserver/cache-handler#109]
Hi!

Not sure if I'm missing something here, but I have tried to connect the same DB to the Cache Handler via either the default `redis` storer and the `go-redis` storer, and the latter does not work. 

The `redis` one works very well - also when there's a configuration issue with the `redis` storer, I can see errors in the logs. (with `log_ level debug`)

When I use the exact same configuration with `go-redis`, it doesn't seem to connect to the DB, but also I can't see anything in the logs.

I'm quite sure this used to work prior to the last Souin version, but I've actually tried to pin v1.7.2 and it didn't work as well.

Here's the config I've used with the `redis` storer:
```
    redis {
      configuration {
        InitAddress server-url:port
        SelectDB 0
        ConnWriteTimeout 5s
        DisableCache true
        BlockingPoolSize 99999
      }
    }
```

And here's the one used with `go-redis`:
```
    redis {
      configuration {
        Addrs server-url:port
        DB 0
        WriteTimeout 5s
        DisableCache true
        PoolSize 99999
      }
    }
```

(P.S. - tried to adjust the `Protocol` command in `go-redis`  from 3 to 2, but didn't seem to change much)

**Comment by darkweak** [comment]
Hey @stpp2 `go-redis` and `redis` storages don't have the exact same configuration. You can find the configuration for `go-redis` here https://docs.souin.io/docs/storages/go-redis/.

**Comment by darkweak** [comment]
You're using `Addr` instead of `Addrs`. 🙂

**Comment by darkweak** [comment]
Sadly I can't reproduce with the following setup

```
#Caddyfile
{
    debug
    log {
        level debug
    }
    cache {
        redis {
            configuration {
                Addrs 127.0.0.1:6379
                DB 0
                WriteTimeout 5s
                DisableCache true
                PoolSize 99999
            }
        }
        default_cache_control public
    }
}

:4443

route {
    cache
    respond "Hello World!"
}
```

```
# compose.yml
services:
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    command: redis-server
```

**Comment by darkweak** [comment]
Can you create a repo that reproduces this behaviour please?

**Comment by darkweak** [comment]
Oh, I think I got it. Can you try with the latest release of Souin?
```
RUN xcaddy build \
  --with github.com/darkweak/souin/plugins/caddy \
  --with github.com/darkweak/storages/go-redis/caddy
```

I released a patch for `go-redis` to retrieved the stored instance because the default client name was not set https://github.com/darkweak/souin/commit/22abb943f2af88b230db2cd413d0d4546dfce113#diff-b6c42537d079f776a1500f1dcc8333e78f34e9bfec8d9e6817994dcb9a480228R124 but this is not yet in the latest release of the cache-handler.
