### ISSUE TITLE
When is this going to launch ?

### ISSUE THREAD

**Issue by amanintech** [caddyserver/cache-handler#18]
A lot of people have referred to this repo when talking about distributed cache of on demand TLS. Is there a timeline on when this would be launched. 
Otherwiese what are current recommended alternatives ?

**Comment by francislavoie** [comment]
When https://github.com/caddyserver/cache-handler/pull/17 is merged, basically. Should be soon.

**Comment by darkweak** [comment]
@amanintech otherwise you could use Souin as caddy module directly. `xcaddy build --with=github.com/darkweak/souin/plugins/caddy` should work.

**Comment by amanintech** [comment]
Hello @darkweak 
I think I have raised the same issue on caddy.community as well. 
https://caddy.community/t/caddy-v2-varnish-on-demand-tls/14269
I am very new to this. Could you help with doing this in docker-compose. I couldn't find any guide as well.

I have been stuck with this problem for months now without any lead so I would appreciate all help

**Comment by francislavoie** [comment]
If you mean you don't know how to build Caddy with plugins in Docker, then please see the docs on Docker Hub, it explains: https://hub.docker.com/_/caddy look for the section "Adding custom Caddy modules"
