### ISSUE TITLE
Cache handler module on https://caddyserver.com/download

### ISSUE THREAD

**Issue by alexandergitter** [caddyserver/cache-handler#19]
Are there any plans to add this Caddy module to the download page at https://caddyserver.com/download?
Thanks!

**Comment by darkweak** [comment]
I guess it would be possible to do that. @mholt who should maintain this in the caddy module download page ?

**Comment by mholt** [comment]
@darkweak Generally the maintainer of the plugin should be the one to do that! :+1: Just create / login to your account at caddyserver.com and register the package there.

**Comment by darkweak** [comment]
I cannot claim the packages under the caddyserver organization. 😅

**Comment by mholt** [comment]
Oh, right -- oops. Either I'll do it or make a way for you to do it...

**Comment by mholt** [comment]
@darkweak Can you tag a release? Then I will just add it to the website.

**Comment by darkweak** [comment]
I have to finish my work on the prometheus export first and after that I'll tag a new version on both sides 👍

**Comment by darkweak** [comment]
Once https://github.com/darkweak/souin/pull/186 is merged I can tag the `v.1.6.0` and refer this version in the cache-handler dependencies

**Comment by darkweak** [comment]
@mholt I think you can refer it on the website now.

**Comment by mholt** [comment]
@darkweak Done! Should appear in the docs soon.
