### ISSUE TITLE
Bug with rewrite directive?

### ISSUE THREAD

**Issue by ueffel** [caddyserver/cache-handler#22]
I found a behaviour that feels weird to me: The module looks for cached responses with the original request URI, but if there is a `rewrite` internally the cache entry is written with the rewritten URI. That means that original request URI does not get a cache hit if requested again.

Minimal example:

```caddyfile
{
	order cache before rewrite
}

http://:80 {

	cache {
		ttl 20s
	}
	rewrite /say/* /respond{path}
	respond /respond/* "{path.2}"

}
```

If I request `http://localhost/say/hi` several times I would think that I get the cached response from the 2nd request onward (within the 20 seconds of course). What actually happens, is that I always get a cache miss.
Requesting `http://localhost/respond/say/hi` as the second request yields me a cache hit.

I know I could just `order cache after rewrite` for this silly use case but I have a more elaborate use case in combination with my [image filter module](https://github.com/ueffel/caddy-imagefilter).

<details>
<summary>elaborate use case</summary>

```caddyfile
{
	order cache before rewrite
	order image_filter before file_server
}

http://:80 {
	@thumbnail {
		path_regexp thumb (?i)/w([0-9]+)(/.+)$
	}
	root .
	handle @thumbnail {
		cache {
			ttl 20s
		}
		rewrite {re.thumb.2}
		image_filter {
			resize {re.thumb.1} 0
		}
	}
}
```

It resizes an image where size is given within the path. So `http://localhost/w100/image.png` would give me a 100 pixel wide thumbnail of `image.png`. Because of the cache misses when `order`ing `cache before rewrite` the image is resized on every request.
If I `order cache after rewrite` here and first request `http://localhost/w100/image.png` and then `http://localhost/w200/image.png` I actually get the 100 pixel wide cached response in the 2nd request even though I should get a newly resized 200px wide response image.

</details>

**Comment by francislavoie** [comment]
FYI @darkweak, you can grab a copy of the original request (before rewrites) with this code:

```go
origReq := r.Context().Value(caddyhttp.OriginalRequestCtxKey).(http.Request)
```

I think the cache module could use this instead of `r` for consistency.

**Comment by darkweak** [comment]
Souin tries to modify at least the request headers and I tried to use the original request from the context but it throws an error that's not a caddy.Replacer pointer.

**Comment by darkweak** [comment]
This commit should fix that https://github.com/darkweak/souin/pull/189/commits/a7ee6b22c03982dd5960e514d6b23d15643c7ed4

**Comment by ueffel** [comment]
I can confirm this fixed in my use cases in https://github.com/darkweak/souin/commit/5c8b76bf3778676ca7f7de43cd26a5200df3e6d4

Thanks!
