### ISSUE TITLE
Suspected cache pollution when adding multiple hosts

### ISSUE THREAD

**Issue by mattvb91** [caddyserver/cache-handler#27]
When adding multiple hostnames to an upstream (?) after a certain amount of time (or certain number of hostnames) there is some kind of cache pollution happening.

Once the cache has been flushed the files return to giving good responses for a certain amount of time before the same happens again.

This has been reproduced in this sample repository here with minimal config: https://github.com/mattvb91/caddy-cache-bug

Samples taken from discussions over from  https://github.com/caddyserver/cache-handler/issues/26#issuecomment-1129657905

![image](https://user-images.githubusercontent.com/11991564/169806541-977a2619-d280-49f2-a166-92deaa0c15ae.png)

After cache flush:

![image](https://user-images.githubusercontent.com/11991564/169806557-5b145470-cc9b-4744-bdff-0b678c6c609f.png)

Here is a video of it happening in action:

https://user-images.githubusercontent.com/11991564/168979843-7b486e28-f4cf-4562-8ab8-ea64caa8d236.mp4

**Comment by darkweak** [comment]
After investigation this is a badger issue
<img width="721" alt="request-souin" src="https://user-images.githubusercontent.com/25440709/170348017-b196bec8-855e-4c7b-baf2-281eddd07ed5.png">
<img width="538" alt="response-souin" src="https://user-images.githubusercontent.com/25440709/170348031-d7d6ae29-fa58-4847-b050-6af8fddc113a.png">
because I request the right key but badger returns the bad key. I don't know why it doesn't clean properly the key when it reach the cache size limit.

**Comment by darkweak** [comment]
https://discuss.dgraph.io/t/badger-doesnt-return-the-good-value/17350

**Comment by mattvb91** [comment]
Aaah thanks for the heads up. I will try at some stage with the redis driver to see if that gets me further just to be able to continue development with the cache system

**Comment by darkweak** [comment]
I will probably switch from badger to rosedb/lotusdb.
I recommend to you to use the embedded olric provider instead using the olric directive in the caddyfile/json config while I'm implementing the new default provider.

**Comment by mattvb91** [comment]
So I can confirm that on the first initial look my CI pipeline runs through using `olric` cache driver so from that side it seems to have improved something and locally it seems to look fine too on first glance.

The requests do come back with correct cache headers etc.. however now on the cache endpoint in my case `/__cache/souin` that lists active cache entries it is now always empty? (Even tho I can see cache correctly working)

**Comment by darkweak** [comment]
I didn't tag the new Souin version, but instead of using github.com/caddyserver/cache-handler as with option you can use github.com/darkweak/souin/plugins/caddy@latest (or the master commit hash). This will include the patch for the surrogate-keys.

**Comment by darkweak** [comment]
Do you have a running olric instance in the same network?
You don't have to specify the url or a configuration if you want to run olric as embedded mode (in memory). I think the documentation is not really explicit about that.

**Comment by mattvb91** [comment]
ah my bad yes I was instantiating a new olric container in my `docker-compose.yml` I didnt realize it was already included in the caddy image! Thats looking way better now.

For anyone else that stumbles on here from google / issue search my current config now looks like this:

```php
                "cache" => [
                    'api'         => [
                        'basepath' => '/__cache',
                        'souin'    => [
                            'basepath' => '/souin',
                            'enable'   => true,
                        ],
                    ],
                    'distributed' => true,
//                    'olric'       => [
//                        'url' => 'olric:3320',
//                    ],
                    "log_level"   => "info",
                    'ttl'         => '3600s',
                ],
```

and I can see the `/__cache/souin` list working. Also on initial glance I can do `PURGE` requests against for example `http://localhost/__cache/souin/GET-test-1-yargvp50.localhost-/api/shop/get/first-product` and I can see it getting removed from the list so its definitely working smoother! 

I will play around with the surrogate-keys later again from the other issue to report back on it!

**Comment by darkweak** [comment]
If you attempt to load the embedded olric provider you just have to set `"olric": {}` in the caddyfile configuration.

**Comment by darkweak** [comment]
If you want to connect to an olric instance you cannot use the embedded provider.
The fact your configuration isn't loaded is awkward, it should try to connect to an olric instance in the same network as your caddy instance 🤔.

**Comment by darkweak** [comment]
```
"apps": {
    "cache": {
      "distributed": true,
      "olric": {},
      "log_level": "info",
      "ttl": "16m40s"
    },
```

**Comment by mattvb91** [comment]
@eth-limo I also have another feature request / question over here that may be relevant to you: https://github.com/darkweak/souin/issues/219 

Would be interested to hear your thoughts on your use case

**Comment by darkweak** [comment]
It should be okay once this branch got merged https://github.com/darkweak/souin/tree/feat/plugins/introduce-beego-plugin. I'm grouping commits for enhancements in this branch.

**Comment by darkweak** [comment]
I can confirm that nutsdb fix the cache pollution (I tested with ~100 websites from your repository).

**Comment by darkweak** [comment]
@mattvb91 You can now try with `--with github.com/darkweak/souin/plugins/caddy` and set the nuts directive to get the cache pollution fix.
```json
"apps": {
  "cache": {
    "nuts": {
      path: "/tmp/nuts-souin"
    },
    "log_level": "info",
    "ttl": "16m40s"
  },
```

**Comment by mattvb91** [comment]
@darkweak this all works great now.

The only last thing that is still an issue now is that the purge request by surrogate key doesn't flush the `STALE_GET` cache entry: https://github.com/caddyserver/cache-handler/issues/26#issuecomment-1138821401

**Comment by darkweak** [comment]
That's weird, everything works on my side 😕
