### ISSUE TITLE
Consider using olric

### ISSUE THREAD

**Issue by mholt** [caddyserver/cache-handler#3]
Olric: https://github.com/buraksezer/olric

It might make a few things easier (for example, eviction) and seems a little less monkey-patched than stuff on top of Groupcache. But I do love how simple Groupcache is to use, and how proven it is...

**Comment by buraksezer** [comment]
Hi @mholt, I'm the author of Olric. It's great to see someone wants to use it! I'm ready for collaboration.

**Comment by mholt** [comment]
@buraksezer Awesome, thanks! This is kind of "up for grabs" right now but maybe I'll find some time this weekend to play with it.

(How'd you find this?)

**Comment by buraksezer** [comment]
@mholt 

I have been working on a possible implementation and I finally have a working prototype. I'm not familiar with the internals of Caddy and I don't know how to pass configuration to Olric, but it works!

Here is my prototype: https://github.com/buraksezer/cache-handler/tree/feature/issue-3

> (How'd you find this?)

I had search the word 'Olric' and saw this issue. What a nice surprise!

**Comment by mholt** [comment]
Awesome! I'm behind on notifications but I will take a look at this soon! Anyone else is also welcome to try it out of course.

**Comment by mholt** [comment]
Had a quick second to look at the code. Not bad, pretty similar to what I got working with groupcache.

I can help on this part if we want to iterate more on this solution:

https://github.com/buraksezer/cache-handler/blob/3765adcc97c5dd95f30d3a9ba1cba8c4c8f5795d/httpcache.go#L191-L199

It'd be good if we could configure Olric's distributed features, so that many Caddy instances could work in a cluster to share a cache.

Also, in general we avoid starting anything (especially in the background) during provisioning if it is expensive:

https://github.com/buraksezer/cache-handler/blob/3765adcc97c5dd95f30d3a9ba1cba8c4c8f5795d/httpcache.go#L86-L92

Maybe this is fine, but we should be able to Stop whatever gets Started.

> I don't know how to pass configuration to Olric

What do you mean by this exactly?

Anyway, great start!

**Comment by danlsgiga** [comment]
I'm interested in this feature to have Caddy reading `Cache-Control` response headers and caching things in case of the origin goes down.

**Comment by dunglas** [comment]
The handler now uses Olric!

**Comment by mholt** [comment]
This is great, thanks for helping with this!!
