### ISSUE TITLE
Caddy exit after enable cache

### ISSUE THREAD

**Issue by 365cent** [caddyserver/cache-handler#38]
![image](https://user-images.githubusercontent.com/74791570/199107524-1efbe88a-a280-4922-af3b-32d42c85ef0f.png)
Hi, I've got a problem running the cache handler module. When I tried to run Caddy with this module enabled, it crashed after a few minutes. I thought I hadn't left enough memory (2G) for caddy, then I got the same issue on my dedicated machine. I tried it with redis enabled and default mode, but none of them worked after pointing my domain to it. However, caddy doesn't exit on my staging machine with this cache-handler module enabled. I am not sure what happened. Could you provide some debug commands so that I can share more information with you? Thanks.

**Comment by francislavoie** [comment]
We'll need to see the full log message. Run `journalctl -u caddy --no-pager | less +G` as per the docs: https://caddyserver.com/docs/running#using-the-service

**Comment by przybylowicz0** [comment]
Hi Francis,
Thanks for the information. I configured my Caddyfile to debug mode. However, I don't see any log print out after I run `journalctl -u caddy --no-pager | less +G`. This time it exited after 4 hours. Please advise if this block of Caddyfile is written correctly. I will try again today.
`
{
        debug
        log {
                level debug
        }
        order cache before rewrite
        cache {
                log_level debug
        }
}
`

**Comment by francislavoie** [comment]
That Caddyfile definitely doesn't look correct, because you're missing newlines and indentation. Please format it correctly!

I don't understand how you could have no logs, because you clearly have a log message as seen by your `service status caddy` call

**Comment by przybylowicz0** [comment]
Hi Francis,
The global options of Caddyfile is something look like this. I put site block in separate file. Do I need to put log level debug on my site configure file. I thought it is global settings and will inherits by sites.
```
{ 
	debug
	log {
		level debug
	}
	servers {
		protocols h1 h2 h3
	}
	order cache before rewrite
	cache {
		log_level debug
	}
}
```

**Comment by darkweak** [comment]
@przybylowicz0 Sorry for the delay. You have to set the cache directive for each sites/routes. It will extend the global configuration and override the properties you redeclare in the site/route block inside the cache directive.

**Comment by przybylowicz0** [comment]
> @przybylowicz0 Sorry for the delay. You have to set the cache directive for each sites/routes. It will extend the global configuration and override the properties you redeclare in the site/route block inside the cache directive.

Hi. It is ok. I already put cache directive for each sites. I was just wondering about should I put log in the site directive. Never mind about that. I think I got the similar output as #39 previously. So I have shut down the testing server and just gonna wait for next update.

**Comment by 11harveyj** [comment]
Hi, I've also had the same problem

`Dec 18 19:14:35 resvmcaddy01 caddy[13626]: {"level":"info","ts":1671390875.435522,"logger":"http.handlers.cache","msg":"DropPrefix called for [GET-apps->Dec 18 19:14:35 resvmcaddy01 caddy[13626]: {"level":"info","ts":1671390875.435563,"logger":"http.handlers.cache","msg":"Writes flushed. Stopping compact>Dec 18 19:14:35 resvmcaddy01 caddy[13626]: {"level":"info","ts":1671390875.43553,"logger":"http.handlers.cache","msg":"DropPrefix called for [GET-apps-h>Dec 18 19:14:35 resvmcaddy01 caddy[13626]: {"level":"info","ts":1671390875.4356313,"logger":"http.handlers.cache","msg":"DropPrefix called for [GET-apps>Dec 18 19:14:35 resvmcaddy01 caddy[13626]: panic: assignment to entry in nil map
Dec 18 19:14:35 resvmcaddy01 caddy[13626]: goroutine 1723224 [running]:
Dec 18 19:14:35 resvmcaddy01 caddy[13626]: net/textproto.MIMEHeader.Set(...)
Dec 18 19:14:35 resvmcaddy01 caddy[13626]:         net/textproto/header.go:22
Dec 18 19:14:35 resvmcaddy01 caddy[13626]: net/http.Header.Set(0x1?, {0x25cbed5?, 0x1b?}, {0xc0002ac0e0, 0x1b})
Dec 18 19:14:35 resvmcaddy01 caddy[13626]:         net/http/header.go:40 +0x96
Dec 18 19:14:35 resvmcaddy01 caddy[13626]: github.com/darkweak/souin/rfc.MissCache(0xc00a561b38, 0x326a740?)
Dec 18 19:14:35 resvmcaddy01 caddy[13626]:         github.com/darkweak/souin@v1.6.22/rfc/cacheStatus.go:56 +0xa2
Dec 18 19:14:35 resvmcaddy01 caddy[13626]: github.com/darkweak/souin/rfc.(*VaryTransport).RoundTrip(0xc0002df5f0, 0xc00b194e00)
Dec 18 19:14:35 resvmcaddy01 caddy[13626]:         github.com/darkweak/souin@v1.6.22/rfc/bridge.go:203 +0x1de
Dec 18 19:14:35 resvmcaddy01 caddy[13626]: github.com/darkweak/souin/rfc.commonCacheControl(0xc00b194e00, {0x3265180, 0xc0002df5f0}, 0x1)
Dec 18 19:14:35 resvmcaddy01 caddy[13626]:         github.com/darkweak/souin@v1.6.22/rfc/bridge.go:52 +0x79
Dec 18 19:14:35 resvmcaddy01 caddy[13626]: github.com/darkweak/souin/rfc.(*VaryTransport).UpdateCacheEventually(0xc0002df5f0, 0xc00b194900)
Dec 18 19:14:35 resvmcaddy01 caddy[13626]:         github.com/darkweak/souin@v1.6.22/rfc/bridge.go:148 +0x91e
Dec 18 19:14:35 resvmcaddy01 caddy[13626]: github.com/caddyserver/cache-handler.(*SouinCaddyPlugin).ServeHTTP.func1({0x0?, 0xc0012e5098?}, 0xc009d74f68?)Dec 18 19:14:35 resvmcaddy01 caddy[13626]:         github.com/caddyserver/cache-handler@v0.3.0/httpcache.go:139 +0x19f
Dec 18 19:14:35 resvmcaddy01 caddy[13626]: github.com/darkweak/souin/plugins.DefaultSouinPluginCallback.func3({0x3276780?, 0xc0012fdfc0?}, 0xc009aed1d0?)Dec 18 19:14:35 resvmcaddy01 caddy[13626]:         github.com/darkweak/souin@v1.6.22/plugins/base.go:207 +0xae
Dec 18 19:14:35 resvmcaddy01 caddy[13626]: created by github.com/darkweak/souin/plugins.DefaultSouinPluginCallback
Dec 18 19:14:35 resvmcaddy01 caddy[13626]:         github.com/darkweak/souin@v1.6.22/plugins/base.go:203 +0x965
Dec 18 19:14:35 resvmcaddy01 systemd[1]: caddy-api.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 18 19:14:35 resvmcaddy01 systemd[1]: caddy-api.service: Failed with result 'exit-code'.
Dec 18 19:14:35 resvmcaddy01 systemd[1]: caddy-api.service: Consumed 2h 38min 55.678s CPU time.`


The lines before this in the log file is unrelated and from well over an hour previously

**Comment by darkweak** [comment]
v0.4.0 has been released! It should fix your issue.

**Comment by 365cent** [comment]
> v0.4.0 has been released! It should fix your issue.

Thanks so much! I really appreciate your help, and I will let you know if I get any other issues.

**Comment by 365cent** [comment]
Hi Darkweak,
Thanks for the hard work you put in, but it seems like new release cache plugin break some pages during repeat visit. Here is two sample website: [https://rp1.ssh.town](https://rp1.ssh.town) (Without cache enabled) and [https://rp2.ssh.town](https://rp2.ssh.town) (Cache enabled). When I trying to visit [https://rp2.ssh.town/index.php?q=aHR0cHM6Ly9mdWxjay5jb20](https://rp2.ssh.town/index.php?q=aHR0cHM6Ly9mdWxjay5jb20) the second time, it looks like the cache plugin breaks the page and returning empty response while this problem is not present on [https://rp1.ssh.town/index.php?q=aHR0cHM6Ly9mdWxjay5jb20](https://rp1.ssh.town/index.php?q=aHR0cHM6Ly9mdWxjay5jb20) (Site without cache enabled). Send me some commands if you require more debug information.

**Comment by darkweak** [comment]
<img width="572" alt="Capture d’écran 2022-12-26 à 10 29 17" src="https://user-images.githubusercontent.com/25440709/209531970-3b705cdf-0b7f-4d63-ac12-5bdc4a423bff.png">
First point, in your application you're trying to load the JS files as the `https://rp2.ssh.town/index.php?q=aHR0cHM6Ly9mdWxjay5jb20`. So I think one of the JS call (on the previous endpoint) returns a valid JS or returns a binary output) but that should return HTML.

Second point, the first index.php call returns the HTTP response headers `Cache-Control: max-age=120, public, max-age=0, must-revalidate` `Cache-Status: Souin; fwd=uri-miss; key=GET-rp2.ssh.town-/index.php?q=aHR0cHM6Ly9mdWxjay5jb20; detail=NOT-CACHEABLE` that means your response is not cacheable (because of your `max-age=0`). 
IMHO that's mostly an issue in your application rather than Souin itself.

**Comment by darkweak** [comment]
To keep you updated:  
@shuaiZend I think the improvements made on the development repository should fix your bug.  
@365cent I'm still investigating.

**Comment by 365cent** [comment]
> To keep you updated: @shuaiZend I think the improvements made on the development repository should fix your bug. @365cent I'm still investigating.

Thanks for your time. I feel like I need to sponsor you somehow, and I will send through mholt after it is fixed. Much thanks!

**Comment by shuaiZend** [comment]
````
Feb 11 17:16:58 VM-zlNr9iaPx8gT caddy[2072409]: panic: Header called after Handler finished
Feb 11 17:16:58 VM-zlNr9iaPx8gT caddy[2072409]: goroutine 851575 [running]:
Feb 11 17:16:58 VM-zlNr9iaPx8gT caddy[2072409]: net/http.(*http2responseWriter).Header(0xc040721220?)
Feb 11 17:16:58 VM-zlNr9iaPx8gT caddy[2072409]:         net/http/h2_bundle.go:6362 +0x7a
Feb 11 17:16:58 VM-zlNr9iaPx8gT caddy[2072409]: github.com/darkweak/souin/plugins.(*CustomWriter).Header(0xc04102dc28?)
Feb 11 17:16:58 VM-zlNr9iaPx8gT caddy[2072409]:         github.com/darkweak/souin@v1.6.23-0.20221115190723-b3c744699c50/plugins/base.go:55 +0x37
Feb 11 17:16:58 VM-zlNr9iaPx8gT caddy[2072409]: github.com/caddyserver/caddy/v2/modules/caddyhttp/encode.(*responseWriter).Close(0xc040721220)
Feb 11 17:16:58 VM-zlNr9iaPx8gT caddy[2072409]:         github.com/caddyserver/caddy/v2@v2.6.2/modules/caddyhttp/encode/encode.go:260 +0x33
Feb 11 17:16:58 VM-zlNr9iaPx8gT caddy[2072409]: github.com/caddyserver/caddy/v2/modules/caddyhttp/encode.(*Encode).ServeHTTP(0xc0006622c0, {0x2420300, 0xc04093f6c0}, 0x764925?, {0x2417700, 0xc0401daa20})
Feb 11 17:16:58 VM-zlNr9iaPx8gT caddy[2072409]:         github.com/caddyserver/caddy/v2@v2.6.2/modules/caddyhttp/encode/encode.go:129 +0xb3
Feb 11 17:16:58 VM-zlNr9iaPx8gT caddy[2072409]: github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0x2420300?, 0xc04093f6c0?}, 0xc025625ef8?)
Feb 11 17:16:58 VM-zlNr9iaPx8gT caddy[2072409]:         github.com/caddyserver/caddy/v2@v2.6.2/modules/caddyhttp/routes.go:290 +0x42
Feb 11 17:16:58 VM-zlNr9iaPx8gT caddy[2072409]: github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x6b45e0?, {0x2420300?, 0xc04093f6c0?}, 0xc025625e58?)
Feb 11 17:16:58 VM-zlNr9iaPx8gT caddy[2072409]:         github.com/caddyserver/caddy/v2@v2.6.2/modules/caddyhttp/caddyhttp.go:58 +0x2f
Feb 11 17:16:58 VM-zlNr9iaPx8gT caddy[2072409]: github.com/darkweak/souin/plugins/caddy.(*SouinCaddyPlugin).ServeHTTP.func1({0x0?, 0xc03e49dc98?}, 0xc025625f68?)
Feb 11 17:16:58 VM-zlNr9iaPx8gT caddy[2072409]:         github.com/darkweak/souin/plugins/caddy@v0.0.0-20221115190723-b3c744699c50/httpcache.go:131 +0x62
Feb 11 17:16:58 VM-zlNr9iaPx8gT caddy[2072409]: github.com/darkweak/souin/plugins.DefaultSouinPluginCallback.func3({0x2420300?, 0xc04093f6c0?}, 0xc040a34570?)
Feb 11 17:16:58 VM-zlNr9iaPx8gT caddy[2072409]:         github.com/darkweak/souin@v1.6.23-0.20221115190723-b3c744699c50/plugins/base.go:210 +0xae
Feb 11 17:16:58 VM-zlNr9iaPx8gT caddy[2072409]: created by github.com/darkweak/souin/plugins.DefaultSouinPluginCallback
Feb 11 17:16:58 VM-zlNr9iaPx8gT caddy[2072409]:         github.com/darkweak/souin@v1.6.23-0.20221115190723-b3c744699c50/plugins/base.go:206 +0x95b
Feb 11 17:16:58 VM-zlNr9iaPx8gT systemd[1]: caddy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 11 17:16:58 VM-zlNr9iaPx8gT systemd[1]: caddy.service: Failed with result 'exit-code'.
````
