### ISSUE TITLE
Prevent caching based on response header

### ISSUE THREAD

**Issue by Sandros94** [caddyserver/cache-handler#65]
So, long story short I'm trying to accelerate an old Drupal 7 website, that more than 95% is anonymous user's traffic and the rest is mostly admins, editors and publishers working on the platform.
Problem is that Drupal 7 doesn't have an `Authorization` header, so any logged user will be cached.

While reading #34 I though that a good solution was to only cache based on the response header, since the bulk of public content is pre-rendered by the cms and tagged accordingly via headers. But to my understanding in Caddy there is no way to run a `matcher` on the response because it is [already too late](https://caddy.community/t/match-by-response-header/9492/2).

A regex based on path isn't an option, since the path of unpublished content is the same as when it would be published.

But, I also have to admit that I still don't fully understand how Souin works, in particular what are the cache keys. Because reading at [this](https://github.com/caddyserver/cache-handler/issues/34#issuecomment-1242893818) and [this](https://github.com/darkweak/souin/issues/66) it almost seems that the functionality of caching only based on response headers is already there, its just I don't understand how to do it.

**Comment by francislavoie** [comment]
I think you can respond with `Cache-Control: no-cache`?

**Comment by Sandros94** [comment]
> I think you can respond with `Cache-Control: no-cache`?

I was indeed expecting that behavior from Drupal, but it doesn't seem consistent. I'm investigating that side as well

**Comment by Sandros94** [comment]
To give an update, so that you are able to judge, and decide to close as not planned or leave it open for potentially a future implementation (I would have liked to open up a draft PR, but I'm not yet that familiar with Go).

### What I've found
Indeed Drupal 7 (well, I've tested only 7.97) does add `Cache-Control: no-cache` to the html page for logged in users, but it also adds `Cache-Control: max-age=N` to the related js for them. Making the actual page be displayed correctly, but not things like form submissions and interactivity.

In further investigation it looks to be a design philosophy compared to an issue: since Drupal is essentially creating an internal, volatile, cache for each user's js ready to be delivered and not regenerating it using PHP on each request (potentially making it quite an expensive task).

**Comment by Sandros94** [comment]
> That's unusual

Indeed and I think this could be down to a Drupal config that aggregates multiple CSS/JS files together. The issue is definitely in the AJAX/jQuery and how they are bundled, but I'm more interested in seeing what a more modern version like Drupal 10 do (I should also look at modules too).

**Comment by darkweak** [comment]
@Sandros94 does the frontend send a `SESSION` cookie?

**Comment by francislavoie** [comment]
> the session is fully handled server-side and it removes any indication of that particular session from headers and cookies

That's wrong. Cookies are used to identify a session in the backend storage. Otherwise the server would have no idea who the client is.

Sometimes it's a cookie like `PHPSESSID` or whatever. It depends on the framework etc.

**Comment by darkweak** [comment]
Drupal adds a session cookie in the browser for authenticated users (e.g. `SESS49960de5880e8c687434170f6476605b`). So you can use the caddy matcher to detect if the request has a cookie with the prefix SESS*, if true, don't use cache, use cache otherwise.

Maybe something like that would work:
```
@authCookie `header({'Cookie':'*SESS*'})`

route @authCookie {
    # only php_fastcgi
}

route {
    cache
    php_fastcgi
}
```

**Comment by francislavoie** [comment]
Or simpler:

```
@noAuthCookie not header Cookie *SESS*
cache @noAuthCookie
```

So cache is only used when there's no session cookie.

**Comment by Sandros94** [comment]
AH! Thank you so much for the explanation!
Quickly found the `SESS` cookie and I'll test the suggested config soon, I'll update.

**Comment by darkweak** [comment]
@Sandros94 we're closing this issue, reopen it if needed.
