### ISSUE TITLE
http.handlers.cache	Reused response from concurrent request with the key...

### ISSUE THREAD

**Issue by DzigaV** [caddyserver/cache-handler#78]
How can I stop this message polluting my logs? I've tried:

```
cache {
    log_level warn
}
```

Am I missing something obvious? 😃

**Comment by darkweak** [comment]
Hey @DzigaV the logger verbosity is based on the caddy log_level 🙂

**Comment by DzigaV** [comment]
Thanks for clarifying. I would like to set a separate log level for this module, but not sure if that's even possible.
