### ISSUE TITLE
Disable Request Coalescing

### ISSUE THREAD

**Issue by DzigaV** [caddyserver/cache-handler#82]
I have some endpoints that will serve a mix of cacheable and uncacheable content. I don't want to run into any performance or security issues caused by request coalescing. How do I disable it?

**Comment by DzigaV** [comment]
I have an unusual use-case. Sometimes a given key will return a generic, cacheable response, which expires after a short TTL. Sometimes the same key will return a unique, user-specific private response, with Cache-Control "no-cache, no-store".

This is what I've done in nginx for years. I was just reading Souin docs when I realised you have request coalescing on by default, which isn't something I'd typically want enabled, given possible security/performance pitfalls.

**Comment by darkweak** [comment]
I'm wondering if the coalescing system will sen only one request to the backend if an authenticated user and an anonymous user try to send the request on the same endpoint (just having an Authorization HTTP request header on the authenticated user). I'll have to do some tests.

Btw, if the response is private, the cache won't store it.

**Comment by DzigaV** [comment]
> I'm wondering if the coalescing system will send only one request to the backend if an authenticated user and an anonymous user try to send the request on the same endpoint (just having an Authorization HTTP request header on the authenticated user). I'll have to do some tests.

The presence or absence of the Authorization header isn't a factor here. This is a cookie-based auth system. The uncacheable content is dynamic and unique to each user. Cacheable content is static, generic and public.

I don't know how Souin is handling coalescing, so I really want to work through this with you, to understand if I have a gaping security hole. Here is a hypothetical scenario that reflects my use-case:

Let's say I have a public asset, like a blog post (/blog/1), that I want to cache for 60 minutes for performance reasons. It's stored in the Souin cache, which serves all subsequent requests for the next 60 mins. In the meantime, I:

a) make this blog post available only to authenticated users.
b) generate different versions of this blog post for each of those users.

After the cache entry expires, multiple simultaneous requests are received for /blog/1. One from Googlebot, another from an unauthenticated visitor, another from a user whose credentials are no longer valid, one from User A and another from User B. You get the picture.

What does Souin do? Has it identified /blog/1 as a target for coalescing, because it was previously cached? Is it going to send the first request to the backend, then serve the same response to all coalesced requests, even if the backend returns no-cache headers? Obviously that would be a security disaster.

What if, given the no-cache header, Souin decides not to serve that response to all clients. Does it unlock all the other requests and _then_ pass them to the backend? That sounds like a performance nightmare.

Then, to complicate things even further, all personalised versions of /blog/1 are deleted after a period of time. It once again becomes a static, public, cacheable asset, for the next 60 minutes. Does Souin refuse to cache it, even though the web server and backend are requesting this? Again, this would be a performance nightmare.

Personally, I don't think request coalescing should be default behaviour for any cache. Middleware shouldn't be making decisions about what data is served to clients, without being instructed.

In nginx, proxy_cache_lock is off by default.

**Comment by darkweak** [comment]
I'm getting it, **BUT** 
- if your backend returns a `Cache-Control: no-cache`, it won't be cacheable so each request must have to fetch the origin server.
- if your backend returns a `Cache-Control: private`, it will generate three cases
  - unauthenticated (one will be sent tho the origin and others unauthenticated will be coalesced and will get the same result as the one sent to the first)
  - authenticated but expired (all authenticated are sent to the origin unless they have the same `Authorization` value)
  - authenticated and valid (all authenticated are sent to the origin unless they have the same `Authorization` value)
Souin detects authenticated requests so it will generate a unique cache key per authenticated user (because it can act as a private cache).

I heard you about a configuration key to disable the coalescing system but the performance issues will be greater than the actual system without the coalescing system. I think what you're trying to achieve could be done by configuring your app responses with a `Vary` header or using the `header_down` subdirective.

IMHO your use case is very specific and we must discuss about all the options we have.

**Comment by DzigaV** [comment]
Thank you for looking at this @darkweak. I appreciate you spending the time. I don't use the Authorization header and I can't rearchitect an application to suit coalescing. I don't want unique cache keys per user. There are no performance downsides to disabling coalescing for me. 

What I do sounds quirky, but it's been in production on nginx for 10 years. But my particular use-case is a distraction I think. Asset cacheability, access policies and implementation details all change. That's what really matters.

Nginx has no coalescing by default. Varnish lets you disable it, likewise the CDNs (using Varnish or otherwise). They point out the severe performance (and possibly security) issues with coalescing, when asset cacheability is changeable. Uncacheable requests being queued and executed in series, for example.

To force coalescing is dictating behaviour to the origin inappropriately imo. Can you help a brother out and create a global option to disable it, otherwise I'm f***ed, not to put too fine a point on it.

**Comment by darkweak** [comment]
@DzigaV can you try with `xcaddy build --with github.com/darkweak/souin/plugins/caddy@46601ccfb6a445669bfad6665c5139c671b962d0 --with github.com/darkweak/souin@46601ccfb6a445669bfad6665c5139c671b962d0` and tell me if that is working as expected please?

**Comment by DzigaV** [comment]
You legend. I will try it as soon as I can.

**Comment by DzigaV** [comment]
@darkweak I tried enabling the global option and had no issues:

```
cache {
		disable_coalescing
	}
```

I haven't actually confirmed that it's not coalescing, but I see you're using a unique key for the singleflightPool call, so it can't be coalescing, right? 😀

**Comment by DzigaV** [comment]
@darkweak I tried enabling the global option and had no issues:

```
cache {
   disable_coalescing
}
```

However, I'm still seeing this in the logs:

`http.handlers.cache	Reused response from concurrent request with the key`

Which doesn't seem right. How can the return value be shared with multiple callers if the key is a UUID?

**Comment by DzigaV** [comment]
@darkweak Looks to be working. No more reused responses.
