### ISSUE TITLE
nutsdb: server hang without log

### ISSUE THREAD

**Issue by daflyinbed** [caddyserver/cache-handler#90]
caddy 2.8.4
cache-handler v0.13.0
in global option:
```
    cache {
        nuts {
            configuration {
                Dir /tmp/nuts-configuration
                EntryIdxMode 1
                RWMode 0
                SegmentSize 1024
                NodeNum 42
                SyncEnable true
                StartFileLoadingMode 1
            }
        }
        storers nuts
    }
```
/tmp/nuts-configuration is created, but caddy response `internal server error` to client.

**Comment by darkweak** [comment]
Hello @daflyinbed do you have some logs about that? Are there any error logs during startup?

**Comment by daflyinbed** [comment]
No. I will try to reproduce this problem in test environment in next few weeks. ( I've reverted back to using Varnish, so this is not my top priority task )

**Comment by darkweak** [comment]
@long2ice same question then, do you have some logs about that? Are there any error logs during startup?  
Can you give me more context?

**Comment by darkweak** [comment]
> For who have same problem, I finally use https://github.com/sillygod/cdp-cache

That's not a suitable solution because the module you are mentioning is not maintained and doesn't implement fully the RFC. By the way I'm already working on a filesystem storage with TTL based eviction but that takes time to work on that beside my daily work and other projects I'm contributing to.
